[canonical-tests]

# Convert an array to linked list, and then from linked list back to array
"3b72d23a-4487-4632-8682-59684c875dd9" = true

# Convert from array, reverse the list, and covert to array
"70484949-cf28-4446-af05-e24f5ae8a265" = true
